#pragma once

// This file is generated. Do not edit manually.
// Generated from .qss theme files.

// Source: /Users/maxvdec/Coding/Projects/Atlas/editor/styling/dark.qss
inline constexpr const char* DARK_THEME =
"* {\n"
"    font-family: \"SF Pro Text\", \"Inter\", \"Segoe UI\", \"Arial\";\n"
"    font-size: 13px;\n"
"    color: #C5C5BE;\n"
"    selection-background-color: #353532;\n"
"    selection-color: #F1F1EC;\n"
"}\n"
"\n"
"QWidget {\n"
"    background: #191918;\n"
"}\n"
"\n"
"QMainWindow,\n"
"QDialog,\n"
"#editorFrame,\n"
"#projectBrowserRoot {\n"
"    background: #121211;\n"
"}\n"
"\n"
"QLabel,\n"
"QCheckBox,\n"
"QRadioButton,\n"
"QToolButton,\n"
"QPushButton {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel:disabled {\n"
"    color: #62625D;\n"
"}\n"
"\n"
"QLabel[muted=\"true\"] {\n"
"    color: #92928B;\n"
"}\n"
"\n"
"QPushButton,\n"
"QToolButton {\n"
"    border: none;\n"
"    border-radius: 7px;\n"
"    padding: 5px 10px;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QToolButton:hover {\n"
"    background: #292928;\n"
"}\n"
"\n"
"QPushButton:checked,\n"
"QToolButton:checked {\n"
"    background: #30302E;\n"
"}\n"
"\n"
"QPushButton:disabled,\n"
"QToolButton:disabled {\n"
"    color: #646460;\n"
"}\n"
"\n"
"QToolButton::menu-indicator {\n"
"    image: none;\n"
"}\n"
"\n"
"QLineEdit,\n"
"QTextEdit,\n"
"QPlainTextEdit {\n"
"    background: #20201F;\n"
"    border: 1px solid transparent;\n"
"    border-radius: 6px;\n"
"    padding: 7px 9px;\n"
"    selection-background-color: #42423E;\n"
"}\n"
"\n"
"QLineEdit:hover,\n"
"QTextEdit:hover,\n"
"QPlainTextEdit:hover {\n"
"    background: #242423;\n"
"}\n"
"\n"
"QLineEdit:focus,\n"
"QTextEdit:focus,\n"
"QPlainTextEdit:focus {\n"
"    border-color: #53534D;\n"
"}\n"
"\n"
"QLineEdit:disabled,\n"
"QTextEdit:disabled,\n"
"QPlainTextEdit:disabled {\n"
"    color: #666660;\n"
"}\n"
"\n"
"QComboBox,\n"
"QSpinBox,\n"
"QDoubleSpinBox,\n"
"QDateEdit,\n"
"QTimeEdit,\n"
"QDateTimeEdit {\n"
"    background: #252524;\n"
"    border: 1px solid transparent;\n"
"    border-radius: 5px;\n"
"    min-height: 24px;\n"
"    padding: 3px 8px;\n"
"    color: #D3D3CC;\n"
"}\n"
"\n"
"QComboBox:hover,\n"
"QSpinBox:hover,\n"
"QDoubleSpinBox:hover {\n"
"    background: #2B2B29;\n"
"}\n"
"\n"
"QComboBox:focus,\n"
"QSpinBox:focus,\n"
"QDoubleSpinBox:focus {\n"
"    border-color: #666660;\n"
"}\n"
"\n"
"QComboBox:disabled,\n"
"QSpinBox:disabled,\n"
"QDoubleSpinBox:disabled {\n"
"    color: #666660;\n"
"}\n"
"\n"
"QComboBox {\n"
"    padding-right: 28px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    width: 26px;\n"
"    border: none;\n"
"}\n"
"\n"
"QComboBox::down-arrow,\n"
"QAbstractSpinBox::down-arrow {\n"
"    image: url(:/editor/assets/chevron-down.svg);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow {\n"
"    image: url(:/editor/assets/chevron-up.svg);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QAbstractSpinBox::up-button,\n"
"QAbstractSpinBox::down-button {\n"
"    background: transparent;\n"
"    border: none;\n"
"    width: 18px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background: #222221;\n"
"    border: 1px solid #393936;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QCheckBox,\n"
"QRadioButton {\n"
"    spacing: 9px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: 1px solid #55554F;\n"
"    border-radius: 4px;\n"
"    background: #232322;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border-color: #999991;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/editor/assets/check.svg);\n"
"    background: #74746C;\n"
"    border-color: #999991;\n"
"}\n"
"\n"
"QCheckBox::indicator:indeterminate {\n"
"    background: #999991;\n"
"    border: 4px solid #44443F;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    background: #232322;\n"
"    border: 1px solid #55554F;\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    width: 8px;\n"
"    height: 8px;\n"
"    background: #DDDDD5;\n"
"    border: 5px solid #55554F;\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    height: 3px;\n"
"    background: #343431;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"    background: #93938A;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: #D5D5CD;\n"
"    border: none;\n"
"    width: 10px;\n"
"    margin: -4px 0;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    background: #292927;\n"
"    border: none;\n"
"    border-radius: 3px;\n"
"    min-height: 6px;\n"
"    text-align: center;\n"
"    color: #F1F1EC;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background: #76766D;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QScrollArea,\n"
"QAbstractScrollArea {\n"
"    background: #191918;\n"
"    border: none;\n"
"}\n"
"\n"
"QAbstractScrollArea::corner {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background: transparent;\n"
"    border: none;\n"
"    width: 8px;\n"
"    margin: 3px 1px;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    background: transparent;\n"
"    border: none;\n"
"    height: 8px;\n"
"    margin: 1px 3px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical,\n"
"QScrollBar::handle:horizontal {\n"
"    background: #3B3B36;\n"
"    border-radius: 3px;\n"
"    min-height: 32px;\n"
"    min-width: 32px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover,\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: #606059;\n"
"}\n"
"\n"
"QScrollBar::add-line,\n"
"QScrollBar::sub-line,\n"
"QScrollBar::add-page,\n"
"QScrollBar::sub-page {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 0;\n"
"    height: 0;\n"
"}\n"
"\n"
"QTreeView,\n"
"QListView,\n"
"QTableView {\n"
"    background: #191918;\n"
"    border: none;\n"
"    outline: none;\n"
"    alternate-background-color: #1D1D1C;\n"
"    show-decoration-selected: 1;\n"
"}\n"
"\n"
"QTreeView::item,\n"
"QListView::item,\n"
"QTableView::item {\n"
"    border: none;\n"
"    padding: 5px 8px;\n"
"}\n"
"\n"
"QTreeView::item:selected,\n"
"QListView::item:selected,\n"
"QTableView::item:selected {\n"
"    background: #30302E;\n"
"    color: #F1F1EC;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background: #191918;\n"
"    border: none;\n"
"    border-bottom: 1px solid #2B2B28;\n"
"    color: #92928B;\n"
"    padding: 9px;\n"
"    font-weight: 400;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    background: transparent;\n"
"    border: none;\n"
"    border-top: 1px solid #2B2B28;\n"
"    margin-top: 26px;\n"
"    padding: 14px 2px 6px 2px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 0;\n"
"    color: #DDDDD6;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    background: #191918;\n"
"    border: none;\n"
"}\n"
"\n"
"QTabBar {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #92928B;\n"
"    padding: 9px 16px;\n"
"    margin: 4px 3px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #2B2B29;\n"
"    color: #EAEAE3;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    color: #EAEAE3;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background: #121211;\n"
"    border: none;\n"
"    padding: 3px 10px;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"    background: transparent;\n"
"    padding: 5px 9px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background: #2B2B29;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QMenu {\n"
"    background: #20201F;\n"
"    border: 1px solid #393936;\n"
"    border-radius: 8px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    background: transparent;\n"
"    padding: 9px 34px 9px 12px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background: #33332F;\n"
"}\n"
"\n"
"QMenu::item:disabled {\n"
"    color: #64645E;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    background: #343431;\n"
"    height: 1px;\n"
"    margin: 6px 10px;\n"
"}\n"
"\n"
"QToolTip {\n"
"    background: #292927;\n"
"    color: #E1E1DA;\n"
"    border: 1px solid #44443E;\n"
"    border-radius: 5px;\n"
"    padding: 6px 9px;\n"
"}\n"
"\n"
"QSplitter::handle {\n"
"    background: #121211;\n"
"}\n"
"\n"
"QSplitter::handle:hover {\n"
"    background: #41413C;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background: #121211;\n"
"    color: #888882;\n"
"    border: none;\n"
"    padding: 3px 14px;\n"
"    min-height: 24px;\n"
"    font-size: 11px;\n"
"}\n"
"\n"
"QStatusBar::item {\n"
"    border: none;\n"
"}\n"
"\n"
"#workspaceBar,\n"
"#workspaceChrome,\n"
"#workspaceIdentity,\n"
"#workspaceIdentityText,\n"
"#workspaceActivity,\n"
"#workspaceUtilities {\n"
"    background: #121211;\n"
"    border: none;\n"
"}\n"
"\n"
"#workspaceBar {\n"
"    padding: 0;\n"
"    spacing: 0;\n"
"}\n"
"\n"
"#workspaceProject {\n"
"    color: #D7D7D0;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"#workspaceSwitcher,\n"
"#workspaceSurface,\n"
"#workspaceHeading,\n"
"#editorWorkspaceStack {\n"
"    background: #191918;\n"
"    border: none;\n"
"}\n"
"\n"
"#workspaceHeading {\n"
"    border-bottom: 1px solid #282825;\n"
"}\n"
"\n"
"#workspaceSwitcher {\n"
"    padding: 0;\n"
"}\n"
"\n"
"#workspaceMark {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#workspaceContextPath,\n"
"#statusVersion,\n"
"#statusRenderer,\n"
"#statusRuntimeText,\n"
"#viewportFpsLabel,\n"
"#viewportShortcutHint {\n"
"    background: transparent;\n"
"    color: #898982;\n"
"    font-size: 11px;\n"
"    border: none;\n"
"}\n"
"\n"
"#statusRuntime {\n"
"    background: transparent;\n"
"}\n"
"\n"
"#sceneTabs {\n"
"    background: #191918;\n"
"    border: none;\n"
"}\n"
"\n"
"#sceneTabs::tab {\n"
"    padding: 9px 14px;\n"
"    min-width: 92px;\n"
"}\n"
"\n"
"#viewportTools {\n"
"    background: #191918;\n"
"}\n"
"\n"
"#viewportToolbar,\n"
"#panelToolbar,\n"
"#materialEditorHeader,\n"
"#postProcessingToolbar,\n"
"#workspaceToolbar {\n"
"    background: #191918;\n"
"    border: none;\n"
"}\n"
"\n"
"#hierarchySearch,\n"
"#contentSearchField {\n"
"    background: #222221;\n"
"    padding: 6px 9px;\n"
"}\n"
"\n"
"#contentPathField {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #A7A7A0;\n"
"}\n"
"\n"
"#inspectorScroll,\n"
"#inspectorContent,\n"
"#materialEditorBody,\n"
"#postProcessingBody,\n"
"#environmentPages,\n"
"#environmentWorkspace,\n"
"#environmentPage {\n"
"    background: #191918;\n"
"    border: none;\n"
"}\n"
"\n"
"#inspectorHeader {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 0;\n"
"}\n"
"\n"
"#inspectorObjectIcon {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#inspectorNameField {\n"
"    background: transparent;\n"
"    border: 1px solid transparent;\n"
"    color: #EAEAE3;\n"
"    font-size: 18px;\n"
"    font-weight: 500;\n"
"    padding: 2px 0;\n"
"}\n"
"\n"
"#inspectorNameField:focus {\n"
"    border-color: #55554F;\n"
"}\n"
"\n"
"#inspectorTypeLabel,\n"
"#inspectorPropertyLabel,\n"
"#materialTexturePath,\n"
"#materialEditorStatus,\n"
"#postProcessingStatus,\n"
"#workspaceStatus,\n"
"#workspaceAutoApply {\n"
"    color: #93938C;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"#inspectorComponent {\n"
"    background: transparent;\n"
"    border: none;\n"
"    border-top: 1px solid #2C2C29;\n"
"    border-radius: 0;\n"
"}\n"
"\n"
"#inspectorComponentHeaderRow,\n"
"#inspectorComponentBody,\n"
"#inspectorPropertyRow,\n"
"#inspectorNestedGroup,\n"
"#inspectorAudioControls {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#inspectorVectorField,\n"
"#inspectorNumericField,\n"
"#inspectorColorField {\n"
"    background: #252524;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#inspectorVectorField QDoubleSpinBox,\n"
"#inspectorNumericField QDoubleSpinBox {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 4px 2px;\n"
"}\n"
"\n"
"#inspectorAxisX,\n"
"#inspectorAxisY,\n"
"#inspectorAxisZ {\n"
"    background: transparent;\n"
"    font-size: 10px;\n"
"    padding: 0 3px;\n"
"}\n"
"\n"
"#inspectorAxisX { color: #CA9290; }\n"
"#inspectorAxisY { color: #9AB696; }\n"
"#inspectorAxisZ { color: #91A9C7; }\n"
"\n"
"#inspectorColorSwatch {\n"
"    border: 1px solid #45453F;\n"
"    border-radius: 4px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"#inspectorColorText {\n"
"    color: #B0B0A8;\n"
"    font-family: \"SF Mono\", \"Menlo\", \"Consolas\";\n"
"    font-size: 11px;\n"
"}\n"
"\n"
"#inspectorNestedTitle,\n"
"#inspectorArrayTitle,\n"
"#materialTextureLabel {\n"
"    color: #C9C9C1;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"#inspectorEmptyTitle,\n"
"#materialEditorEmpty,\n"
"#postProcessingEmpty {\n"
"    color: #C7C7BF;\n"
"    font-size: 15px;\n"
"    font-weight: 400;\n"
"}\n"
"\n"
"#inspectorEmptyHint,\n"
"#environmentPageSubtitle,\n"
"#dialogHeroSubtitle {\n"
"    color: #92928B;\n"
"}\n"
"\n"
"#materialEditorTitle,\n"
"#postProcessingTitle,\n"
"#postProcessingSectionTitle,\n"
"#workspaceTitle,\n"
"#inspectorCameraTitle {\n"
"    color: #D9D9D2;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"#materialPreview {\n"
"    background: #151514;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"#materialTextureSlot {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 6px 0;\n"
"}\n"
"\n"
"#materialTexturePreview {\n"
"    background: #242423;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"#environmentCategories {\n"
"    background: #191918;\n"
"    border: none;\n"
"    padding: 8px;\n"
"}\n"
"\n"
"#environmentPageTitle {\n"
"    color: #E7E7E0;\n"
"    font-size: 22px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"ads--CDockContainerWidget,\n"
"ads--CDockContainerWidget > QSplitter,\n"
"ads--CDockContainerWidget ads--CDockSplitter::handle {\n"
"    background: #121211;\n"
"}\n"
"\n"
"ads--CDockAreaWidget,\n"
"ads--CDockAreaWidget[focused=\"true\"] {\n"
"    background: #191918;\n"
"    border: none;\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"ads--CDockAreaTitleBar,\n"
"ads--CDockAreaWidget[focused=\"true\"] ads--CDockAreaTitleBar {\n"
"    background: #191918;\n"
"    border: none;\n"
"    min-height: 40px;\n"
"}\n"
"\n"
"#tabsContainerWidget {\n"
"    background: transparent;\n"
"}\n"
"\n"
"ads--CDockWidgetTab,\n"
"ads--CDockWidgetTab[activeTab=\"true\"],\n"
"ads--CDockWidgetTab[focused=\"true\"] {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 3px 10px;\n"
"    margin: 3px;\n"
"}\n"
"\n"
"ads--CDockWidgetTab #dockWidgetTabLabel {\n"
"    color: #A1A19A;\n"
"    font-size: 13px;\n"
"    padding: 4px 0;\n"
"}\n"
"\n"
"ads--CDockWidgetTab[activeTab=\"true\"] #dockWidgetTabLabel {\n"
"    color: #DADAD3;\n"
"}\n"
"\n"
"ads--CTitleBarButton,\n"
"#tabCloseButton,\n"
"#dockAreaCloseButton,\n"
"#detachGroupButton,\n"
"#dockAreaAutoHideButton,\n"
"#dockAreaMinimizeButton,\n"
"#tabsMenuButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 4px;\n"
"    min-width: 18px;\n"
"    min-height: 18px;\n"
"}\n"
"\n"
"ads--CTitleBarButton:hover,\n"
"#tabCloseButton:hover {\n"
"    background: #2B2B29;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"ads--CDockWidget {\n"
"    background: #191918;\n"
"}\n"
"\n"
"ads--CAutoHideSideBar,\n"
"#sideTabsContainerWidget {\n"
"    background: #121211;\n"
"}\n"
"\n"
"ads--CAutoHideTab {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 7px;\n"
"}\n"
"\n"
"#projectSidebar {\n"
"    background: #121211;\n"
"    border: none;\n"
"}\n"
"\n"
"#projectBrowserContent {\n"
"    background: #191918;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#projectBrand {\n"
"    color: #E7E7E0;\n"
"    font-size: 16px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"#projectSidebarVersion,\n"
"#projectSidebarCaption,\n"
"#projectPath,\n"
"#projectDate,\n"
"#projectBrowserSubtitle,\n"
"#dialogSubtitle,\n"
"#emptyStateSubtitle,\n"
"#templateDescription {\n"
"    color: #92928B;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"#projectBrowserTitle,\n"
"#dialogTitle {\n"
"    color: #EAEAE4;\n"
"    font-size: 28px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"#projectSearch {\n"
"    background: #222221;\n"
"    padding: 10px 12px;\n"
"}\n"
"\n"
"#projectList {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#projectRow {\n"
"    background: transparent;\n"
"    border: none;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"#projectRow:hover {\n"
"    background: #242423;\n"
"}\n"
"\n"
"#projectRow[selected=\"true\"] {\n"
"    background: #30302E;\n"
"}\n"
"\n"
"#projectName {\n"
"    color: #DEDED7;\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"}\n"
"\n"
"#projectIcon,\n"
"#templateIcon {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#rendererBadge {\n"
"    background: #262624;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"    color: #ABABA2;\n"
"    font-size: 10px;\n"
"    padding: 4px 7px;\n"
"}\n"
"\n"
"#projectEmptyState {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#emptyStateTitle {\n"
"    color: #CFCFC7;\n"
"    font-size: 20px;\n"
"    font-weight: 400;\n"
"}\n"
"\n"
"QFrame[templateCard=\"true\"] {\n"
"    background: #20201F;\n"
"    border: 1px solid transparent;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QFrame[templateCard=\"true\"][selected=\"true\"] {\n"
"    background: #2A2A28;\n"
"    border-color: #66665F;\n"
"}\n"
"\n"
"#templateOption,\n"
"#fieldLabel {\n"
"    color: #BDBDB5;\n"
"    font-weight: 400;\n"
"}\n"
"\n"
"#dialogError {\n"
"    color: #D69C95;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"#dialogHero {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"#dialogHeroIcon {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"#dialogHeroTitle {\n"
"    color: #E3E3DB;\n"
"    font-size: 22px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"#exportSummary {\n"
"    background: #1D1D1C;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    color: #9C9C94;\n"
"    padding: 12px;\n"
"}\n"
"\n"
"#exportLog,\n"
"#runtimeErrors {\n"
"    background: #161615;\n"
"    border: none;\n"
"    padding: 12px;\n"
"    font-family: \"SF Mono\", \"Menlo\", \"Consolas\";\n"
"    font-size: 12px;\n"
"    color: #C3BAB1;\n"
"}\n"
"\n"
"#commandPaletteDialog,\n"
"#globalSearchDialog {\n"
"    background: #191918;\n"
"    border: 1px solid #373733;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#commandPaletteSearch,\n"
"#globalSearchField {\n"
"    background: transparent;\n"
"    border: none;\n"
"    border-bottom: 1px solid #30302C;\n"
"    border-radius: 0;\n"
"    padding: 15px 12px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"#commandPaletteList,\n"
"#globalSearchResults {\n"
"    background: transparent;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"#paletteHint,\n"
"#projectListHint {\n"
"    background: transparent;\n"
"    color: #7E7E77;\n"
"    font-size: 11px;\n"
"    padding: 7px 12px;\n"
"}\n"
"\n"
"#splashCard {\n"
"    background: #191918;\n"
"    border: 1px solid #343430;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"#atlasSplash,\n"
"#splashIcon {\n"
"    background: transparent;\n"
"}\n"
"\n"
"#splashTitle {\n"
"    color: #ECECE6;\n"
"    font-size: 36px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"#splashVersion,\n"
"#splashCompany,\n"
"#splashWarning {\n"
"    color: #91918A;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"#splashStatus {\n"
"    color: #BFBFB7;\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"#splashProgress {\n"
"    background: #2C2C28;\n"
"    border: none;\n"
"    min-height: 0;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"#splashProgress::chunk {\n"
"    background: #BCBCB2;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QPushButton:default {\n"
"    background: #E5E5E1;\n"
"    color: #191918;\n"
"}\n"
"\n"
"#projectSectionLabel {\n"
"    color: #82827B;\n"
"    font-size: 12px;\n"
"    padding: 3px 10px;\n"
"}\n"
"\n"
"#searchPreviewPane {\n"
"    background: #171716;\n"
"    border: none;\n"
"    border-left: 1px solid #30302C;\n"
"}\n"
"\n"
"#searchPreviewText {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 0;\n"
"    font-family: \"SF Mono\", \"Menlo\", \"Consolas\";\n"
"    font-size: 12px;\n"
"    color: #B6B6AF;\n"
"}\n"
"\n"
"#projectRow[available=\"false\"] #projectName {\n"
"    color: #82827B;\n"
"}\n"
"\n"
"QAbstractSpinBox QLineEdit {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 0;\n"
"    min-height: 0;\n"
"}\n"
"\n"
"#inspectorVectorField {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#inspectorAxisField {\n"
"    background: #252524;\n"
"    border: 1px solid transparent;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"#inspectorAxisField:hover {\n"
"    background: #2C2C29;\n"
"    border-color: #44443F;\n"
"}\n"
"\n"
"#inspectorAxisField QDoubleSpinBox {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 5px 2px;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"#inspectorNumberField,\n"
"#inspectorNameField,\n"
"#inspectorColorText {\n"
"    min-height: 26px;\n"
"}\n"
"\n"
"#inspectorAxisX,\n"
"#inspectorAxisY,\n"
"#inspectorAxisZ {\n"
"    padding: 0;\n"
"    font-size: 11px;\n"
"}\n"
"\n"
"QTabBar::close-button {\n"
"    image: url(:/editor/assets/close.svg);\n"
"    width: 14px;\n"
"    height: 14px;\n"
"    padding: 5px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QTabBar::close-button:hover,\n"
"#tabCloseButton:hover,\n"
"#dockAreaCloseButton:hover {\n"
"    background: #343431;\n"
"}\n"
;
