#pragma once

// This file is generated. Do not edit manually.
// Generated from .qss theme files.

// Source: /Users/maxvdec/Coding/Projects/Atlas/editor/styling/dark.qss
inline constexpr const char* DARK_THEME =
"* {\n"
"    font-family: \"SF Pro Text\", \"Inter\", \"Segoe UI\", \"Arial\";\n"
"    font-size: 11px;\n"
"    color: #D6D6D6;\n"
"    selection-background-color: #4772B3;\n"
"    selection-color: #FFFFFF;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: #1C1C1C;\n"
"    color: #D6D6D6;\n"
"}\n"
"\n"
"QMainWindow,\n"
"QDialog,\n"
"QFrame {\n"
"    background-color: #1C1C1C;\n"
"}\n"
"\n"
"QLabel {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QLabel:disabled {\n"
"    color: #566174;\n"
"}\n"
"\n"
"QToolTip {\n"
"    background-color: #303030;\n"
"    color: #F7F9FC;\n"
"    border: 1px solid #505050;\n"
"    border-radius: 4px;\n"
"    padding: 4px 6px;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    background-color: #242424;\n"
"    border: 1px solid #3B3B3B;\n"
"    border-radius: 4px;\n"
"    margin-top: 13px;\n"
"    padding: 7px;\n"
"    color: #F1F4F8;\n"
"    font-weight: 650;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    left: 9px;\n"
"    padding: 0 6px;\n"
"    color: #AEB8C8;\n"
"    background-color: #242424;\n"
"}\n"
"\n"
"QScrollArea,\n"
"QAbstractScrollArea {\n"
"    background-color: #202020;\n"
"    border: none;\n"
"}\n"
"\n"
"QAbstractScrollArea::corner {\n"
"    background-color: #202020;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    background-color: transparent;\n"
"    width: 9px;\n"
"    margin: 2px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    background-color: transparent;\n"
"    height: 9px;\n"
"    margin: 2px;\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical,\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: #4A4A4A;\n"
"    border-radius: 4px;\n"
"    min-height: 30px;\n"
"    min-width: 30px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover,\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background-color: #666666;\n"
"}\n"
"\n"
"QScrollBar::add-line,\n"
"QScrollBar::sub-line,\n"
"QScrollBar::add-page,\n"
"QScrollBar::sub-page {\n"
"    background: none;\n"
"    border: none;\n"
"    width: 0;\n"
"    height: 0;\n"
"}\n"
"\n"
"QPushButton,\n"
"QToolButton {\n"
"    background-color: #303030;\n"
"    border: 1px solid #464646;\n"
"    border-radius: 3px;\n"
"    padding: 3px 8px;\n"
"    color: #D8D8D8;\n"
"    min-height: 22px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QPushButton:hover,\n"
"QToolButton:hover {\n"
"    background-color: #3A3A3A;\n"
"    border-color: #606060;\n"
"}\n"
"\n"
"QPushButton:pressed,\n"
"QToolButton:pressed {\n"
"    background-color: #242424;\n"
"    border-color: #4772B3;\n"
"}\n"
"\n"
"QPushButton:checked,\n"
"QToolButton:checked {\n"
"    background-color: #3B5F8A;\n"
"    border-color: #5D8BC0;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QPushButton:default,\n"
"#primaryAction {\n"
"    background-color: #4772B3;\n"
"    border-color: #6791C9;\n"
"    color: #FFFFFF;\n"
"    font-weight: 650;\n"
"}\n"
"\n"
"QPushButton:default:hover,\n"
"#primaryAction:hover {\n"
"    background-color: #5682C2;\n"
"    border-color: #7AA1D4;\n"
"}\n"
"\n"
"QPushButton:disabled,\n"
"QToolButton:disabled {\n"
"    background-color: #242424;\n"
"    border-color: #333333;\n"
"    color: #686868;\n"
"}\n"
"\n"
"QToolButton::menu-indicator {\n"
"    image: none;\n"
"}\n"
"\n"
"QLineEdit,\n"
"QTextEdit,\n"
"QPlainTextEdit,\n"
"QComboBox,\n"
"QSpinBox,\n"
"QDoubleSpinBox,\n"
"QDateEdit,\n"
"QTimeEdit,\n"
"QDateTimeEdit {\n"
"    background-color: #181818;\n"
"    border: 1px solid #3D3D3D;\n"
"    border-radius: 3px;\n"
"    padding: 3px 7px;\n"
"    color: #E2E2E2;\n"
"    min-height: 22px;\n"
"}\n"
"\n"
"QLineEdit:hover,\n"
"QTextEdit:hover,\n"
"QPlainTextEdit:hover,\n"
"QComboBox:hover,\n"
"QSpinBox:hover,\n"
"QDoubleSpinBox:hover {\n"
"    border-color: #5A5A5A;\n"
"}\n"
"\n"
"QLineEdit:focus,\n"
"QTextEdit:focus,\n"
"QPlainTextEdit:focus,\n"
"QComboBox:focus,\n"
"QSpinBox:focus,\n"
"QDoubleSpinBox:focus {\n"
"    background-color: #222222;\n"
"    border-color: #5D8BC0;\n"
"}\n"
"\n"
"QLineEdit:disabled,\n"
"QTextEdit:disabled,\n"
"QComboBox:disabled,\n"
"QSpinBox:disabled,\n"
"QDoubleSpinBox:disabled {\n"
"    background-color: #202020;\n"
"    border-color: #303030;\n"
"    color: #666666;\n"
"}\n"
"\n"
"QComboBox {\n"
"    padding-right: 24px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 22px;\n"
"    border-left: 1px solid #3B3B3B;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #292929;\n"
"    border: 1px solid #4B4B4B;\n"
"    border-radius: 4px;\n"
"    padding: 3px;\n"
"    selection-background-color: #3B5F8A;\n"
"}\n"
"\n"
"QAbstractSpinBox::up-button,\n"
"QAbstractSpinBox::down-button {\n"
"    background-color: #292929;\n"
"    border: none;\n"
"    width: 16px;\n"
"}\n"
"\n"
"QAbstractSpinBox::up-button:hover,\n"
"QAbstractSpinBox::down-button:hover {\n"
"    background-color: #3E3E3E;\n"
"}\n"
"\n"
"QCheckBox,\n"
"QRadioButton {\n"
"    spacing: 7px;\n"
"    color: #C9D1DE;\n"
"}\n"
"\n"
"QCheckBox::indicator,\n"
"QRadioButton::indicator {\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    background-color: #171717;\n"
"    border: 1px solid #555555;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QCheckBox::indicator:hover,\n"
"QRadioButton::indicator:hover {\n"
"    border-color: #777777;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked,\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #4772B3;\n"
"    border-color: #6D98CE;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    background-color: #353535;\n"
"    height: 4px;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background-color: #5D8BC0;\n"
"    border: 2px solid #A0B9D7;\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QProgressBar {\n"
"    background-color: #262626;\n"
"    border: 1px solid #424242;\n"
"    border-radius: 3px;\n"
"    height: 8px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #4772B3;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QTreeView,\n"
"QListView,\n"
"QListWidget,\n"
"QTableView,\n"
"QTableWidget {\n"
"    background-color: #202020;\n"
"    alternate-background-color: #242424;\n"
"    border: none;\n"
"    color: #DCE3EC;\n"
"    show-decoration-selected: 1;\n"
"}\n"
"\n"
"QTreeView::item,\n"
"QListView::item,\n"
"QListWidget::item,\n"
"QTableView::item,\n"
"QTableWidget::item {\n"
"    border: 1px solid transparent;\n"
"    border-radius: 2px;\n"
"    padding: 3px 5px;\n"
"}\n"
"\n"
"QTreeView::item:hover,\n"
"QListView::item:hover,\n"
"QListWidget::item:hover,\n"
"QTableView::item:hover,\n"
"QTableWidget::item:hover {\n"
"    background-color: #303030;\n"
"    border-color: #464646;\n"
"}\n"
"\n"
"QTreeView::item:selected,\n"
"QListView::item:selected,\n"
"QListWidget::item:selected,\n"
"QTableView::item:selected,\n"
"QTableWidget::item:selected {\n"
"    background-color: #3B5F8A;\n"
"    border-color: #5D8BC0;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QHeaderView {\n"
"    background-color: #202020;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #292929;\n"
"    border: none;\n"
"    border-right: 1px solid #404040;\n"
"    border-bottom: 1px solid #404040;\n"
"    padding: 5px 7px;\n"
"    color: #98A4B7;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    background-color: #202020;\n"
"    border: 1px solid #3B3B3B;\n"
"    border-radius: 0;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #252525;\n"
"    border: none;\n"
"    border-right: 1px solid #393939;\n"
"    border-bottom: 1px solid #3B3B3B;\n"
"    color: #7F8B9D;\n"
"    min-width: 88px;\n"
"    padding: 5px 10px;\n"
"    margin: 1px 0;\n"
"    border-radius: 0;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: #303030;\n"
"    color: #C8D1DF;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #333333;\n"
"    color: #F2F5F9;\n"
"    border-bottom: 2px solid #5D8BC0;\n"
"}\n"
"\n"
"QMenuBar#atlasMenuBar {\n"
"    background-color: #181818;\n"
"    border-bottom: 1px solid #303030;\n"
"    padding: 1px 6px;\n"
"}\n"
"\n"
"QMenuBar#atlasMenuBar::item {\n"
"    background: transparent;\n"
"    color: #B8C2D0;\n"
"    padding: 5px 9px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QMenuBar#atlasMenuBar::item:selected,\n"
"QMenuBar#atlasMenuBar::item:pressed {\n"
"    background-color: #343434;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QMenu {\n"
"    background-color: #292929;\n"
"    border: 1px solid #515151;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QMenu::item {\n"
"    background: transparent;\n"
"    border-radius: 2px;\n"
"    padding: 6px 32px 6px 9px;\n"
"    color: #DCE3EC;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"    background-color: #3B5F8A;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QMenu::item:disabled {\n"
"    color: #596477;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"    background-color: #424242;\n"
"    height: 1px;\n"
"    margin: 5px 8px;\n"
"}\n"
"\n"
"QSplitter::handle {\n"
"    background-color: #111111;\n"
"}\n"
"\n"
"QSplitter::handle:horizontal {\n"
"    width: 4px;\n"
"}\n"
"\n"
"QSplitter::handle:vertical {\n"
"    height: 4px;\n"
"}\n"
"\n"
"QSplitter::handle:hover {\n"
"    background-color: #5D8BC0;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background-color: #181818;\n"
"    border-top: 1px solid #303030;\n"
"    color: #8490A4;\n"
"}\n"
"\n"
"#atlasStatusBar {\n"
"    min-height: 23px;\n"
"    padding: 0 6px;\n"
"}\n"
"\n"
"#statusRuntimeIcon {\n"
"    padding: 0;\n"
"}\n"
"\n"
"#statusRuntime {\n"
"    background: transparent;\n"
"    border-right: 1px solid #343434;\n"
"}\n"
"\n"
"#statusRuntimeText {\n"
"    color: #9BA79F;\n"
"    font-size: 10px;\n"
"}\n"
"\n"
"#statusRenderer {\n"
"    background-color: #292929;\n"
"    border: 1px solid #454545;\n"
"    border-radius: 3px;\n"
"    color: #B6BCB8;\n"
"    font-size: 9px;\n"
"    font-weight: 700;\n"
"    padding: 2px 6px;\n"
"}\n"
"\n"
"#statusVersion {\n"
"    color: #68758A;\n"
"    font-size: 9px;\n"
"    padding: 0 6px;\n"
"}\n"
"\n"
"#workspaceBar {\n"
"    background-color: #202020;\n"
"    border: none;\n"
"    border-bottom: 1px solid #3B3B3B;\n"
"    spacing: 4px;\n"
"    padding: 3px 6px 3px 0;\n"
"    min-height: 38px;\n"
"}\n"
"\n"
"#workspaceIdentity {\n"
"    background: transparent;\n"
"    border-right: 1px solid #424242;\n"
"}\n"
"\n"
"#workspaceMark {\n"
"    background-color: #292929;\n"
"    border: 1px solid #3F3F3F;\n"
"    border-radius: 4px;\n"
"    padding: 3px;\n"
"}\n"
"\n"
"#workspaceIdentityText {\n"
"    background: transparent;\n"
"}\n"
"\n"
"#workspaceBrand {\n"
"    color: #8C8C8C;\n"
"    font-size: 8px;\n"
"    font-weight: 750;\n"
"}\n"
"\n"
"#workspaceProject {\n"
"    color: #EFEFEF;\n"
"    font-size: 12px;\n"
"    font-weight: 650;\n"
"}\n"
"\n"
"#workspaceSwitcher {\n"
"    background-color: #181818;\n"
"    border: 1px solid #383838;\n"
"    border-radius: 4px;\n"
"    margin-left: 7px;\n"
"}\n"
"\n"
"#workspaceModeButton {\n"
"    background-color: #222222;\n"
"    border: 1px solid transparent;\n"
"    border-radius: 3px;\n"
"    color: #A0A0A0;\n"
"    padding: 3px 9px;\n"
"    min-height: 22px;\n"
"}\n"
"\n"
"#workspaceModeButton:hover {\n"
"    background-color: #333333;\n"
"    color: #E2E2E2;\n"
"}\n"
"\n"
"#workspaceModeButton:checked {\n"
"    background-color: #3B5F8A;\n"
"    border-color: #5D8BC0;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"#workspaceCommandButton,\n"
"#workspaceUtilityButton,\n"
"#workspaceBuildButton,\n"
"#workspaceLaunchButton {\n"
"    min-width: 42px;\n"
"    padding: 3px 9px;\n"
"    margin-left: 2px;\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"#workspaceCommandButton,\n"
"#workspaceUtilityButton,\n"
"#workspaceBuildButton {\n"
"    background-color: #292929;\n"
"    border-color: #444444;\n"
"}\n"
"\n"
"#workspaceLaunchButton {\n"
"    background-color: #3F684F;\n"
"    border-color: #5A8B6B;\n"
"    color: #FFFFFF;\n"
"    font-weight: 650;\n"
"}\n"
"\n"
"#workspaceCommandButton:hover,\n"
"#workspaceUtilityButton:hover,\n"
"#workspaceBuildButton:hover,\n"
"#workspaceLaunchButton:hover {\n"
"    background-color: #3A3A3A;\n"
"    border-color: #606060;\n"
"}\n"
"\n"
"#workspaceLaunchButton:hover {\n"
"    background-color: #4E7B5E;\n"
"    border-color: #6B9B79;\n"
"}\n"
"\n"
"#workspaceContextBar {\n"
"    background-color: #292929;\n"
"    border: none;\n"
"    border-bottom: 1px solid #3C3C3C;\n"
"    spacing: 2px;\n"
"    padding: 1px 5px 1px 0;\n"
"    min-height: 27px;\n"
"}\n"
"\n"
"#workspaceBreadcrumb {\n"
"    background: transparent;\n"
"    border-right: 1px solid #414141;\n"
"}\n"
"\n"
"#workspaceContextIcon {\n"
"    background: transparent;\n"
"}\n"
"\n"
"#workspaceContextTitle {\n"
"    color: #E0E0E0;\n"
"    font-weight: 650;\n"
"}\n"
"\n"
"#workspaceContextPath {\n"
"    color: #7F7F7F;\n"
"}\n"
"\n"
"#workspacePanelButton {\n"
"    background-color: transparent;\n"
"    border-color: transparent;\n"
"    color: #8F8F8F;\n"
"    padding: 2px 7px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"#workspacePanelButton:hover {\n"
"    background-color: #363636;\n"
"    color: #DADADA;\n"
"}\n"
"\n"
"#workspacePanelButton:checked {\n"
"    background-color: #333333;\n"
"    border-color: #4A4A4A;\n"
"    color: #EAEAEA;\n"
"}\n"
"\n"
"#sceneTabs {\n"
"    background-color: #181818;\n"
"    border-bottom: 1px solid #3B3B3B;\n"
"}\n"
"\n"
"#sceneTabs::tab {\n"
"    background-color: #242424;\n"
"    border-right: 1px solid #3A3A3A;\n"
"    color: #7F8B9D;\n"
"    min-width: 112px;\n"
"    padding: 5px 10px;\n"
"    margin: 0;\n"
"    border-radius: 0;\n"
"}\n"
"\n"
"#sceneTabs::tab:selected {\n"
"    background-color: #333333;\n"
"    color: #F3F6FA;\n"
"    border-bottom: 2px solid #5D8BC0;\n"
"}\n"
"\n"
"#viewportTools {\n"
"    background-color: #151515;\n"
"}\n"
"\n"
"#viewportToolbar {\n"
"    background-color: #292929;\n"
"    border-bottom: 1px solid #3B3B3B;\n"
"}\n"
"\n"
"#viewportPlaybackButton,\n"
"#viewportModeButton,\n"
"#viewportOptionButton,\n"
"#viewportShadingButton {\n"
"    background-color: #292C2F;\n"
"    border-color: #414549;\n"
"    min-width: 25px;\n"
"    min-height: 22px;\n"
"    padding: 3px 5px;\n"
"}\n"
"\n"
"#viewportPlaybackButton:hover,\n"
"#viewportModeButton:hover,\n"
"#viewportOptionButton:hover,\n"
"#viewportShadingButton:hover {\n"
"    background-color: #363A3E;\n"
"    border-color: #5A5F65;\n"
"}\n"
"\n"
"#viewportModeButton:checked,\n"
"#viewportShadingButton:checked {\n"
"    background-color: #3A4248;\n"
"    border-color: #6F7B84;\n"
"}\n"
"\n"
"#viewportFpsLabel {\n"
"    color: #9CA5A0;\n"
"    font-size: 10px;\n"
"    font-weight: 650;\n"
"}\n"
"\n"
"#viewportShortcutHint {\n"
"    background-color: #141517;\n"
"    border-top: 1px solid #303236;\n"
"    color: #68758A;\n"
"    font-size: 10px;\n"
"    padding: 3px 7px;\n"
"}\n"
"\n"
"#panelToolbar,\n"
"#materialEditorHeader,\n"
"#postProcessingToolbar,\n"
"#workspaceToolbar {\n"
"    background-color: #292929;\n"
"    border-bottom: 1px solid #404040;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"#panelAddButton,\n"
"#materialSaveButton,\n"
"#workspaceApplyButton {\n"
"    background-color: #333333;\n"
"    border-color: #4C4C4C;\n"
"    color: #D8DBDE;\n"
"}\n"
"\n"
"#panelMoreButton,\n"
"#browserNavigationButton,\n"
"#browserRevealButton {\n"
"    background-color: transparent;\n"
"    border-color: transparent;\n"
"    min-width: 24px;\n"
"}\n"
"\n"
"#panelMoreButton:hover,\n"
"#browserNavigationButton:hover,\n"
"#browserRevealButton:hover {\n"
"    background-color: #34373A;\n"
"    border-color: #484C50;\n"
"}\n"
"\n"
"#contentPathField {\n"
"    background-color: #1B1D1F;\n"
"    color: #8490A4;\n"
"    font-size: 11px;\n"
"}\n"
"\n"
"#contentSearchField {\n"
"    min-width: 130px;\n"
"}\n"
"\n"
"QTreeView#hierarchyTree {\n"
"    background-color: #202020;\n"
"    border-top: 1px solid #303030;\n"
"    padding: 3px 2px;\n"
"}\n"
"\n"
"QTreeView#hierarchyTree::item {\n"
"    min-height: 22px;\n"
"    padding: 1px 6px;\n"
"}\n"
"\n"
"QTreeView#hierarchyTree::item:hover {\n"
"    background-color: #303030;\n"
"    border-color: #444444;\n"
"}\n"
"\n"
"QTreeView#hierarchyTree::item:selected {\n"
"    background-color: #3B5F8A;\n"
"    border-color: #5D8BC0;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QListView#contentGrid {\n"
"    background-color: #1C1C1C;\n"
"    border-top: 1px solid #303030;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QListView#contentGrid::item {\n"
"    background-color: #252525;\n"
"    border: 1px solid #363636;\n"
"    border-radius: 4px;\n"
"    padding: 6px;\n"
"    color: #BCC6D4;\n"
"}\n"
"\n"
"QListView#contentGrid::item:hover {\n"
"    background-color: #303030;\n"
"    border-color: #505050;\n"
"}\n"
"\n"
"QListView#contentGrid::item:selected {\n"
"    background-color: #3B5F8A;\n"
"    border-color: #5D8BC0;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"QScrollArea#inspectorScroll,\n"
"#inspectorContent,\n"
"#materialEditorBody,\n"
"#postProcessingBody {\n"
"    background-color: #202020;\n"
"    border: none;\n"
"}\n"
"\n"
"#inspectorHeader {\n"
"    background-color: #292929;\n"
"    border: 1px solid #414141;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"#inspectorObjectIcon {\n"
"    background-color: #343434;\n"
"    border: 1px solid #4E4E4E;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"#inspectorNameField {\n"
"    background: transparent;\n"
"    border: 1px solid transparent;\n"
"    color: #F3F6FA;\n"
"    font-size: 14px;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"#inspectorNameField:hover,\n"
"#inspectorNameField:focus {\n"
"    background-color: #202020;\n"
"    border-color: #5A5A5A;\n"
"}\n"
"\n"
"#inspectorTypeLabel {\n"
"    color: #7E8A9E;\n"
"    font-size: 10px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#inspectorComponent {\n"
"    background-color: #242424;\n"
"    border: 1px solid #3D3D3D;\n"
"    border-radius: 3px;\n"
"    margin-top: 2px;\n"
"}\n"
"\n"
"#inspectorComponentHeaderRow {\n"
"    background-color: #2D2D2D;\n"
"    border-bottom: 1px solid #3B3B3B;\n"
"    border-radius: 3px 3px 0 0;\n"
"}\n"
"\n"
"#inspectorComponentHeader {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #E8ECF2;\n"
"    font-weight: 650;\n"
"    text-align: left;\n"
"    padding: 4px 7px;\n"
"}\n"
"\n"
"#inspectorComponentHeader:hover {\n"
"    background-color: #383838;\n"
"}\n"
"\n"
"#inspectorComponentRemoveButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    min-width: 22px;\n"
"}\n"
"\n"
"#inspectorComponentRemoveButton:hover {\n"
"    background-color: #3A3031;\n"
"    border: 1px solid #695556;\n"
"}\n"
"\n"
"#inspectorComponentBody {\n"
"    background-color: #242424;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"#inspectorPropertyRow {\n"
"    background: transparent;\n"
"    min-height: 27px;\n"
"}\n"
"\n"
"#inspectorPropertyLabel {\n"
"    color: #929EB0;\n"
"    font-size: 11px;\n"
"}\n"
"\n"
"#inspectorVectorField,\n"
"#inspectorColorField,\n"
"#inspectorNumericField {\n"
"    background-color: #181818;\n"
"    border: 1px solid #3D3D3D;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"#inspectorVectorField QDoubleSpinBox,\n"
"#inspectorNumericField QDoubleSpinBox {\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#inspectorAxisX,\n"
"#inspectorAxisY,\n"
"#inspectorAxisZ {\n"
"    border-radius: 2px;\n"
"    color: #F1F1F1;\n"
"    font-size: 9px;\n"
"    font-weight: 750;\n"
"    padding: 2px 5px;\n"
"}\n"
"\n"
"#inspectorAxisX {\n"
"    background-color: #874747;\n"
"}\n"
"\n"
"#inspectorAxisY {\n"
"    background-color: #477451;\n"
"}\n"
"\n"
"#inspectorAxisZ {\n"
"    background-color: #435E86;\n"
"}\n"
"\n"
"#inspectorSyncButton,\n"
"#inspectorArrayButton {\n"
"    background: transparent;\n"
"    border-color: transparent;\n"
"    min-width: 22px;\n"
"}\n"
"\n"
"#inspectorSyncButton[matched=\"true\"] {\n"
"    background-color: #343936;\n"
"    border-color: #555F59;\n"
"    color: #B6BEB9;\n"
"}\n"
"\n"
"#inspectorColorSwatch {\n"
"    background-color: #292929;\n"
"    border: 1px solid #4D4D4D;\n"
"    border-radius: 3px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"#inspectorColorText {\n"
"    color: #9CA8BA;\n"
"    font-family: \"Menlo\";\n"
"    font-size: 10px;\n"
"}\n"
"\n"
"#inspectorNestedGroup {\n"
"    background-color: #202020;\n"
"    border: 1px solid #383838;\n"
"    border-radius: 3px;\n"
"    margin: 3px 0;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"#inspectorNestedTitle,\n"
"#inspectorArrayTitle {\n"
"    color: #AEB8C8;\n"
"    font-weight: 650;\n"
"}\n"
"\n"
"#inspectorEmptyTitle,\n"
"#materialEditorEmpty,\n"
"#postProcessingEmpty {\n"
"    color: #C4CDDA;\n"
"    font-size: 14px;\n"
"    font-weight: 650;\n"
"}\n"
"\n"
"#inspectorEmptyHint {\n"
"    color: #728096;\n"
"}\n"
"\n"
"#inspectorOpenAssetButton,\n"
"#inspectorAddComponentButton {\n"
"    background-color: #292929;\n"
"    border: 1px dashed #5A5A5A;\n"
"    color: #C7D0DD;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"#inspectorAddComponentButton:hover {\n"
"    background-color: #363636;\n"
"    border-color: #666666;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"#inspectorAudioControls {\n"
"    background-color: #202020;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"#materialEditorTitle,\n"
"#postProcessingTitle,\n"
"#postProcessingSectionTitle,\n"
"#inspectorCameraTitle,\n"
"#workspaceTitle {\n"
"    color: #F3F6FA;\n"
"    font-size: 13px;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"#materialEditorStatus,\n"
"#postProcessingStatus,\n"
"#workspaceStatus,\n"
"#workspaceAutoApply {\n"
"    color: #7E8A9E;\n"
"    font-size: 10px;\n"
"}\n"
"\n"
"#materialPreview {\n"
"    background-color: #151515;\n"
"    border: 1px solid #444444;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#materialColorButton {\n"
"    background-color: #292929;\n"
"    border-color: #454545;\n"
"    border-radius: 3px;\n"
"    color: #C9CDD0;\n"
"    text-align: left;\n"
"    padding: 4px 8px;\n"
"}\n"
"\n"
"#materialColorButton:hover {\n"
"    background-color: #34383B;\n"
"    border-color: #5A5F65;\n"
"}\n"
"\n"
"#materialTextureSlot {\n"
"    background-color: #252525;\n"
"    border: 1px solid #404040;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"#materialTexturePreview {\n"
"    background-color: #1A1A1A;\n"
"    border: 1px solid #494949;\n"
"    border-radius: 3px;\n"
"    color: #9E897D;\n"
"    font-weight: 750;\n"
"}\n"
"\n"
"#materialTextureLabel {\n"
"    color: #D6DDE7;\n"
"    font-weight: 650;\n"
"}\n"
"\n"
"#materialTexturePath {\n"
"    color: #7D899C;\n"
"}\n"
"\n"
"#environmentPages,\n"
"#environmentWorkspace,\n"
"#environmentPage {\n"
"    background-color: #202020;\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget#environmentCategories {\n"
"    background-color: #1B1B1B;\n"
"    border-right: 1px solid #3B3B3B;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QListWidget#environmentCategories::item {\n"
"    padding: 6px 8px;\n"
"    margin: 2px 0;\n"
"}\n"
"\n"
"QListWidget#environmentCategories::item:selected {\n"
"    background-color: #3B5F8A;\n"
"    border-left: 2px solid #5D8BC0;\n"
"}\n"
"\n"
"#environmentPageTitle {\n"
"    color: #F3F6FA;\n"
"    font-size: 17px;\n"
"    font-weight: 750;\n"
"}\n"
"\n"
"#environmentPageSubtitle {\n"
"    color: #778499;\n"
"}\n"
"\n"
"QGroupBox#environmentSection {\n"
"    background-color: #242424;\n"
"    border-color: #3B3B3B;\n"
"}\n"
"\n"
"ads--CDockContainerWidget {\n"
"    background-color: #111111;\n"
"}\n"
"\n"
"ads--CDockContainerWidget > QSplitter {\n"
"    background-color: #111111;\n"
"}\n"
"\n"
"ads--CDockContainerWidget ads--CDockSplitter::handle {\n"
"    background-color: #111111;\n"
"}\n"
"\n"
"ads--CDockContainerWidget ads--CDockSplitter::handle:hover {\n"
"    background-color: #5D8BC0;\n"
"}\n"
"\n"
"ads--CDockAreaWidget {\n"
"    background-color: #202020;\n"
"    border: 1px solid #343434;\n"
"}\n"
"\n"
"ads--CDockAreaWidget[focused=\"true\"] {\n"
"    border-color: #4A6382;\n"
"}\n"
"\n"
"ads--CDockAreaTitleBar {\n"
"    background-color: #292929;\n"
"    border-bottom: 1px solid #3B3B3B;\n"
"    min-height: 25px;\n"
"}\n"
"\n"
"ads--CDockAreaWidget[focused=\"true\"] ads--CDockAreaTitleBar {\n"
"    background-color: #2D2D2D;\n"
"}\n"
"\n"
"#tabsContainerWidget {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"ads--CTitleBarButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    border-radius: 2px;\n"
"    min-width: 22px;\n"
"    min-height: 22px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"ads--CTitleBarButton:hover {\n"
"    background-color: #404040;\n"
"}\n"
"\n"
"ads--CDockWidgetTab {\n"
"    background-color: #292929;\n"
"    border: none;\n"
"    border-right: 1px solid #3A3A3A;\n"
"    border-bottom: 1px solid #3B3B3B;\n"
"    padding: 1px 5px;\n"
"    margin: 1px 0;\n"
"    border-radius: 0;\n"
"}\n"
"\n"
"ads--CDockWidgetTab:hover {\n"
"    background-color: #333333;\n"
"}\n"
"\n"
"ads--CDockWidgetTab[activeTab=\"true\"] {\n"
"    background-color: #333333;\n"
"    border-bottom: 2px solid #5D8BC0;\n"
"}\n"
"\n"
"ads--CDockWidgetTab[focused=\"true\"] {\n"
"    background-color: #303030;\n"
"}\n"
"\n"
"ads--CDockWidgetTab #dockWidgetTabLabel {\n"
"    color: #7F8B9D;\n"
"    font-size: 11px;\n"
"    padding: 4px 2px;\n"
"}\n"
"\n"
"ads--CDockWidgetTab[activeTab=\"true\"] #dockWidgetTabLabel,\n"
"ads--CDockWidgetTab[focused=\"true\"] #dockWidgetTabLabel {\n"
"    color: #F1F4F8;\n"
"}\n"
"\n"
"#tabCloseButton,\n"
"#dockAreaCloseButton,\n"
"#detachGroupButton,\n"
"#dockAreaAutoHideButton,\n"
"#dockAreaMinimizeButton,\n"
"#tabsMenuButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    min-width: 20px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"#tabCloseButton:hover,\n"
"#dockAreaCloseButton:hover,\n"
"#detachGroupButton:hover,\n"
"#dockAreaAutoHideButton:hover,\n"
"#dockAreaMinimizeButton:hover,\n"
"#tabsMenuButton:hover {\n"
"    background-color: #424549;\n"
"}\n"
"\n"
"ads--CDockWidget {\n"
"    background-color: #202020;\n"
"}\n"
"\n"
"ads--CAutoHideSideBar,\n"
"#sideTabsContainerWidget {\n"
"    background-color: #141517;\n"
"}\n"
"\n"
"ads--CAutoHideTab {\n"
"    background-color: #202224;\n"
"    border: 1px solid #404448;\n"
"    color: #7F8B9D;\n"
"    padding: 4px;\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"ads--CAutoHideTab:hover,\n"
"ads--CAutoHideTab[activeTab=\"true\"] {\n"
"    background-color: #393F44;\n"
"    border-color: #66737C;\n"
"    color: #FFFFFF;\n"
"}\n"
"\n"
"#projectBrowserRoot,\n"
"#projectBrowserContent {\n"
"    background-color: #18191B;\n"
"}\n"
"\n"
"#projectSidebar {\n"
"    background-color: #151618;\n"
"    border-right: 1px solid #303236;\n"
"}\n"
"\n"
"#projectBrand {\n"
"    color: #F5F7FA;\n"
"    font-size: 16px;\n"
"    font-weight: 750;\n"
"}\n"
"\n"
"#projectSidebarVersion {\n"
"    color: #68758A;\n"
"    font-size: 10px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"#projectNavSelected {\n"
"    background-color: #34383C;\n"
"    border: 1px solid #51575C;\n"
"    border-left: 3px solid #79868F;\n"
"    border-radius: 10px;\n"
"    color: #DCE9FA;\n"
"    padding: 6px 9px;\n"
"    text-align: left;\n"
"}\n"
"\n"
"#projectNavSelected:disabled {\n"
"    color: #DCE9FA;\n"
"}\n"
"\n"
"#projectBrowserTitle,\n"
"#dialogTitle {\n"
"    color: #F4F6FA;\n"
"    font-size: 24px;\n"
"    font-weight: 750;\n"
"}\n"
"\n"
"#projectBrowserSubtitle,\n"
"#dialogSubtitle,\n"
"#emptyStateSubtitle,\n"
"#templateDescription {\n"
"    color: #7F8B9D;\n"
"}\n"
"\n"
"#projectSearch {\n"
"    background-color: #202224;\n"
"    border: 1px solid #43474B;\n"
"    border-radius: 11px;\n"
"    padding: 7px 9px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"#projectSearch:focus {\n"
"    border-color: #71808A;\n"
"}\n"
"\n"
"#projectList {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"#projectList::item {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 0;\n"
"}\n"
"\n"
"#projectRow {\n"
"    background-color: #242628;\n"
"    border: 1px solid #3B3E41;\n"
"    border-radius: 13px;\n"
"}\n"
"\n"
"#projectRow:hover {\n"
"    background-color: #2C2F32;\n"
"    border-color: #565B61;\n"
"}\n"
"\n"
"#projectRow[available=\"false\"] {\n"
"    background-color: #202224;\n"
"    border-color: #303235;\n"
"}\n"
"\n"
"#projectIcon,\n"
"#templateIcon {\n"
"    background-color: #303337;\n"
"    border: 1px solid #484C50;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#projectName {\n"
"    color: #EEF2F7;\n"
"    font-size: 14px;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"#projectPath,\n"
"#projectDate {\n"
"    color: #768398;\n"
"    font-size: 10px;\n"
"}\n"
"\n"
"#rendererBadge {\n"
"    background-color: #2C302E;\n"
"    border: 1px solid #494F4B;\n"
"    border-radius: 8px;\n"
"    color: #B4BBB6;\n"
"    padding: 3px 7px;\n"
"    font-size: 9px;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"#projectMoreButton {\n"
"    background: transparent;\n"
"    border-color: transparent;\n"
"}\n"
"\n"
"#projectMoreButton:hover {\n"
"    background-color: #3E4246;\n"
"    border-color: #51565B;\n"
"}\n"
"\n"
"#projectEmptyState {\n"
"    background-color: #1E2022;\n"
"    border: 1px dashed #484C51;\n"
"    border-radius: 14px;\n"
"}\n"
"\n"
"#emptyStateTitle {\n"
"    color: #CDD5E1;\n"
"    font-size: 16px;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"#createProjectDialog {\n"
"    background-color: #1E2022;\n"
"}\n"
"\n"
"QFrame[templateCard=\"true\"] {\n"
"    background-color: #242628;\n"
"    border: 1px solid #42464A;\n"
"    border-radius: 13px;\n"
"}\n"
"\n"
"QFrame[templateCard=\"true\"]:hover {\n"
"    background-color: #2B2E31;\n"
"    border-color: #5A5F65;\n"
"}\n"
"\n"
"QFrame[templateCard=\"true\"][selected=\"true\"] {\n"
"    background-color: #393F44;\n"
"    border-color: #66737C;\n"
"}\n"
"\n"
"#templateOption {\n"
"    color: #E7ECF3;\n"
"    font-weight: 650;\n"
"}\n"
"\n"
"#fieldLabel {\n"
"    color: #AAB5C5;\n"
"    font-size: 11px;\n"
"    font-weight: 650;\n"
"}\n"
"\n"
"#dialogError {\n"
"    color: #FF7D8A;\n"
"    font-size: 11px;\n"
"}\n"
"\n"
"QPushButton[secondary=\"true\"] {\n"
"    background-color: #292C2F;\n"
"    border-color: #494D52;\n"
"}\n"
"\n"
"QPushButton[secondary=\"true\"]:hover {\n"
"    background-color: #363A3E;\n"
"    border-color: #5D6268;\n"
"}\n"
"\n"
"#projectSettingsDialog,\n"
"#exportDialog {\n"
"    background-color: #18191B;\n"
"}\n"
"\n"
"#dialogHero {\n"
"    background-color: #242628;\n"
"    border: 1px solid #42464A;\n"
"    border-radius: 13px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"#dialogHeroIcon {\n"
"    background-color: #2B3034;\n"
"    border: 1px solid #50575C;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"#dialogHeroTitle {\n"
"    color: #F3F6FA;\n"
"    font-size: 17px;\n"
"    font-weight: 750;\n"
"}\n"
"\n"
"#dialogHeroSubtitle,\n"
"#exportSummary {\n"
"    color: #7F8B9D;\n"
"}\n"
"\n"
"#exportSummary {\n"
"    background-color: #232527;\n"
"    border: 1px solid #3B3E42;\n"
"    border-radius: 10px;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"#exportLog {\n"
"    background-color: #141517;\n"
"    border-color: #404448;\n"
"    color: #B7BDBC;\n"
"    font-family: \"Menlo\";\n"
"    font-size: 10px;\n"
"}\n"
"\n"
"#commandPaletteDialog,\n"
"#globalSearchDialog {\n"
"    background-color: #202224;\n"
"    border: 1px solid #5A5F65;\n"
"    border-radius: 14px;\n"
"}\n"
"\n"
"#commandPaletteSearch,\n"
"#globalSearchField {\n"
"    background-color: #1A1C1E;\n"
"    border: 1px solid #505459;\n"
"    border-radius: 11px;\n"
"    padding: 7px 9px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"#commandPaletteSearch:focus,\n"
"#globalSearchField:focus {\n"
"    border-color: #71808A;\n"
"}\n"
"\n"
"#commandPaletteList,\n"
"#globalSearchResults {\n"
"    background-color: #202224;\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"#commandPaletteList::item,\n"
"#globalSearchResults::item {\n"
"    min-height: 30px;\n"
"    padding: 6px 8px;\n"
"}\n"
;
