module Types;

enum TextureType {
    Color,
    Specular,
    Cubemap,
    Depth,
    DepthCube,
    Normal,
    Parallax,
    SSAONoise,
    SSAO,
    Metallic,
    Roughness,
    AO,
    Opacity,
    HDR,
    PBRPack
}

enum EffectType {
    Invert,
    Grayscale,
    Sharpen,
    Blur,
    EdgeDetection,
    ColorCorrection,
    MotionBlur,
    ChromaticAberration,
    Posterization,
    Pixelation,
    Dilation,
    FilmGrain,
}


