set(SHADER_INPUT_DIR "${CMAKE_SOURCE_DIR}/shaders")
string(TOLOWER "${BACKEND}" SHADER_BACKEND_ARG)
set(SHADER_GENERATED_INCLUDE_DIR "${CMAKE_BINARY_DIR}/generated/${SHADER_BACKEND_ARG}")
set(SHADER_OUTPUT_FILE "${SHADER_GENERATED_INCLUDE_DIR}/atlas/core/default_shaders.h")
include_directories(BEFORE "${SHADER_GENERATED_INCLUDE_DIR}")

find_package(Python3 COMPONENTS Interpreter REQUIRED)
find_program(SLANGC_EXECUTABLE NAMES slangc REQUIRED)
find_program(SPIRV_CROSS_EXECUTABLE NAMES spirv-cross REQUIRED)

set(ATLAS_PHOTON_BACKEND "AUTO" CACHE STRING "Native Photon shaders: AUTO, METAL, VULKAN, OFF")
set_property(CACHE ATLAS_PHOTON_BACKEND PROPERTY STRINGS AUTO METAL VULKAN OFF)
string(TOUPPER "${ATLAS_PHOTON_BACKEND}" PHOTON_SHADER_BACKEND)
if (PHOTON_SHADER_BACKEND STREQUAL "AUTO")
    if (BACKEND_METAL)
        set(PHOTON_SHADER_BACKEND "METAL")
    else ()
        set(PHOTON_SHADER_BACKEND "OFF")
    endif ()
endif ()
if (NOT PHOTON_SHADER_BACKEND MATCHES "^(METAL|VULKAN|OFF)$")
    message(FATAL_ERROR "Invalid ATLAS_PHOTON_BACKEND='${ATLAS_PHOTON_BACKEND}'")
endif ()
if (NOT PHOTON_SHADER_BACKEND STREQUAL "OFF" AND NOT PHOTON_SHADER_BACKEND STREQUAL BACKEND)
    message(FATAL_ERROR "Photon's shader backend must match BACKEND")
endif ()
string(TOLOWER "${PHOTON_SHADER_BACKEND}" PHOTON_SHADER_BACKEND_ARG)
if (NOT PHOTON_SHADER_BACKEND STREQUAL "OFF" AND
    NOT EXISTS "${SHADER_INPUT_DIR}/photon/${PHOTON_SHADER_BACKEND_ARG}/manifest.json")
    message(FATAL_ERROR "Photon ${PHOTON_SHADER_BACKEND} shaders are not implemented; add shaders/photon/${PHOTON_SHADER_BACKEND_ARG}/manifest.json first")
endif ()

file(GLOB_RECURSE SHADER_SOURCES CONFIGURE_DEPENDS
        "${SHADER_INPUT_DIR}/*.slang"
        "${SHADER_INPUT_DIR}/*.metal"
        "${SHADER_INPUT_DIR}/*.spv"
        "${SHADER_INPUT_DIR}/*.json"
)

set(RUNTIME_SCRIPT_INPUT_DIR "${CMAKE_SOURCE_DIR}/runtime/scripts")
set(RUNTIME_SCRIPT_OUTPUT_FILE "${CMAKE_SOURCE_DIR}/include/atlas/runtime/atlasScripts.h")
file(GLOB_RECURSE RUNTIME_SCRIPT_SOURCES CONFIGURE_DEPENDS
        ${RUNTIME_SCRIPT_INPUT_DIR}/*.js
        ${RUNTIME_SCRIPT_INPUT_DIR}/*.mjs
)

set(SHADER_GENERATION_CONFIG "${SHADER_GENERATED_INCLUDE_DIR}/shader-config.txt")
file(GENERATE OUTPUT "${SHADER_GENERATION_CONFIG}"
     CONTENT "${BACKEND}\n${PHOTON_SHADER_BACKEND}\n${SLANGC_EXECUTABLE}\n${SPIRV_CROSS_EXECUTABLE}\n")
add_custom_command(
        OUTPUT "${SHADER_OUTPUT_FILE}"
        COMMAND ${Python3_EXECUTABLE} "${CMAKE_SOURCE_DIR}/scripts/pack_shaders.py"
                "${SHADER_INPUT_DIR}" "${SHADER_OUTPUT_FILE}" "${SHADER_BACKEND_ARG}"
                --slangc "${SLANGC_EXECUTABLE}"
                --spirv-cross "${SPIRV_CROSS_EXECUTABLE}"
                --photon-backend "${PHOTON_SHADER_BACKEND_ARG}"
        DEPENDS ${SHADER_SOURCES} "${CMAKE_SOURCE_DIR}/scripts/pack_shaders.py"
                "${SHADER_GENERATION_CONFIG}" "${SLANGC_EXECUTABLE}" "${SPIRV_CROSS_EXECUTABLE}"
        VERBATIM
)
add_custom_target(generate_shaders DEPENDS "${SHADER_OUTPUT_FILE}")

