name: Build and Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          brew install cmake ninja qt@6 sdl3 glm openal-soft assimp vulkan-loader molten-vk vulkan-validationlayers spirv-cross spirv-headers spirv-tools
      - name: Configure Qt
        run: |
          echo "$(brew --prefix qt@6)/bin" >> "$GITHUB_PATH"
          echo "CMAKE_PREFIX_PATH=$(brew --prefix qt@6)" >> "$GITHUB_ENV"
      - name: Build
        run: |
          cmake -S . -B build -DBACKEND=AUTO -G Ninja
          cmake --build build --parallel 4
